# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20161216_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venueurl',
            field=models.URLField(blank=True, default='', verbose_name='venueurl'),
        ),
    ]
