# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_venue_venueurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_ics',
            field=models.URLField(blank=True, default='', verbose_name='website'),
        ),
    ]
