# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_event_ics'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venueid',
            field=models.PositiveIntegerField(null=True, verbose_name='venueid'),
        ),
    ]
